apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /ingress-nginx
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  name: ingress-nginx
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|ingress-nginx'
